module_name: Products in the same category
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - product page
  - crossselling
  - similar products
description_short: Adds a block on the product page that displays products from the same category.
description: description.md
images:
  - image-1.png
license: AFL 3.0
